language: ruby
rvm:
  - 2.0.0-p451
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: VC2DrHIN1Pyuk9Y10gYRWgD18NTypwOQEzFDs9ySI0MIUfKUq+/QvZN0wYX1MsD92Mai3MO2hKelfkyg9VRvybGd3GRHiaalF232aJ3/merNq53C/gpSbY35dr9pxoSLgAEGBioF8cSRDsbLf7adVXC+LQwwIy50GRYA8qQKGzQ=
  app: save-my-money
  on:
    branch: master
    repo: ezekielriva/save-my-money
  run:
    - bundle exec rake db:migrate
    - bundle exec rake cleanup
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV="test" RACK_ENV="test" bundle exec rspec -cfn spec
